# Generated by Django 5.2.6 on 2025-10-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=255)),
                (
                    "category_image",
                    models.ImageField(blank=True, upload_to="photos/categories"),
                ),
                ("added_on", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Category",
            },
        ),
    ]
