# Generated by Django 5.2.6 on 2025-09-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name=models.CharField(max_length=50, unique=True)),
        ),
    ]
