# Generated by Django 5.2.6 on 2025-10-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="added_on",
        ),
    ]
